### ISSUE TITLE
Need to reevaluate ClusterRole access

### ISSUE THREAD

**Issue by juliev0** [numaproj-labs/numaplane#243]
**Describe the bug**

We may need to be able to do:
```
- apiGroups:
  - ""
  resources:
  - secrets
  - namespaces
  verbs:
  - 'get'
  - 'list'
  - 'watch'
```

I'm not sure offhand about what we need "namespaces" for, but the code was failing without it (see [this](https://github.com/numaproj-labs/numaplane/issues/242) issue).

Need to also see if anything else is missing.

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
