### ISSUE TITLE
Git fetch should consider auth when creds are needed

### ISSUE THREAD

**Issue by xdevxy** [numaproj-labs/numaplane#244]
**Describe the bug**
We need to consider adding auth for fetch options when creds are needed.

**To Reproduce**

1. Apply the following git sync,
 ```
apiVersion: numaplane.numaproj.io/v1alpha1
kind: GitSync
metadata:
  name: oss-analytics-shakira-test-control-repo1-qal-usw2-eks
  namespace: oss-analytics-shakiratestcontrolrepo1-usw2-qal
spec:
  path: ""
  repoUrl: https://github.intuit.com/oss-analytics/shakira-test-control-repo1-deployment.git
  targetRevision: environments/qal-usw2-eks
  raw: {}
  destination:
    cluster: ip-msaas-ppd-usw2-k8s
    namespace: oss-analytics-shakiratestcontrolrepo1-usw2-qal
```
2. Reference not found bug is shown,

`
 {"level":"error","GitSync name":"gitsync-example","repo":"https://github.intuit.com/oss-analytics/numaplane-control-plane.git","error":"reference not found","logger":"numaplane.synchronizer","revision":"test-julie","repo":"https://github.intuit.com/oss-analytics/numaplane-control-plane.git","caller":"logger/logger.go:166","ts":"2024-04-25T19:31:47.004321538Z","msg":"error resolving the revision"}
`

**Expected behavior**
Resourcesw should syncing successfully

**Screenshots**

---

**Message from the maintainers**:

Impacted by this bug? Give it a 👍. We often sort issues this way to know what to prioritize.
