### ISSUE TITLE
Add Repository type field in GitSync

### ISSUE THREAD

**Issue by chandankumar4** [numaproj-labs/numaplane#90]
Add repository type field in GitSync CR which could be like below:

_Originally posted by @xdevxy in https://github.com/numaproj-labs/numaplane/pull/86#discussion_r1488561068_

**Comment by xdevxy** [comment]
> Below is the the configs I have came up with, feel free to modify it...
> 
> Note: `repositoryPath` is replaced with `source`
> 
> ```
> For Kustomize:
> ---
> ...
> spec:
>   source:
>     kustomize:
>       name: numaflow
>       path: config/namespace-install
>       repoUrl: https://github.com/numaproj/numaflow.git
>       targetRevision: main
> ...
> ```
> 
> For Helm:
> 
> ```
> spec:
>   source:
>     helm:
>       name: numaflow
>       path: charts/numaflow
>       repoUrl: https://github.com/numaproj/helm-charts.git
>       targetRevision: main
>       valueFiles:
>         - values-1.yaml
>         - values-2.yaml
>       parameters:
>         - name: "service.type"
>           value: LoadBalancer
> ...
> ```
> 
> For Directory:
> 
> ```
> spec:
>   source:
>     directory:
>       name: numaflow
>       path: sample-pipeline
>       repoUrl: https://github.com/xdevxy/numaflow-example-pipelines.git
>       targetRevision: main
> ...
> ```
I would recommend make the `name` `path`, `repoUrl` right under spec. And for `directory` and `kustomize` we don't  have any configurations needed ATM, so we can leave it empty for now and added when we find the needs.

For Kustomize:
---
...
spec:
  source:
    name: numaflow
    path: config/namespace-install
    repoUrl: https://github.com/numaproj/numaflow.git
    targetRevision: main
    kustomize:
      ...
   directory:
     ...
   helm:
      valueFiles:
        - values-1.yaml
        - values-2.yaml
      parameters:
        - name: "service.type"
          value: LoadBalancer

...

**Comment by juliev0** [comment]
As mentioned on slack, I personally like the name "raw" vs "directory" as I feel like "directory" is not an orthogonal concept to "kustomize" and "helm", both of which use directories, but feel free to disagree.

I see the @xdevxy included `parameters` in her example. FYI that this is what we're using [now](https://github.intuit.com/kubernetes/cluster-deployments/blob/master/apps/application-set/numaflow/numaflow-wave1-application-set.yaml#L21) to Numaflow cluster-level resources.

**Comment by chandankumar4** [comment]
> 
> I would recommend make the `name` `path`, `repoUrl` right under spec. And for `directory` and `kustomize` we don't have any configurations needed ATM, so we can leave it empty for now and added when we find the needs.
> 
> For example,
> 
> ```
> spec:
>   source:
>     name: numaflow
>     path: config/namespace-install
>     repoUrl: https://github.com/numaproj/numaflow.git
>     targetRevision: main
>    kustomize:
>      ...
>    directory:
>      ...
>    helm:
>       valueFiles:
>         - values-1.yaml
>         - values-2.yaml
>       parameters:
>         - name: "service.type"
>           value: LoadBalancer
> 
> ...
> ```

@xdevxy the example provided above is confusing as per the description above?
> I would recommend make the `name` `path`, `repoUrl` right under spec 

did you meant something like below?
```
spec:
  name: numaflow
  path: config/namespace-install
  repoUrl: https://github.com/numaproj/numaflow.git
  targetRevision: main
  source:
    kustomize: {}
    ...
    directory: {}
    ...
    helm:
      valueFiles:
        - values-1.yaml
        - values-2.yaml
      parameters:
        - name: "service.type"
          value: LoadBalancer
```

**Comment by xdevxy** [comment]
Sorry @chandankumar4 I messed up with the indent. Updated it. we can also take out the source as we only have one source now.
```
spec:
  name: numaflow
  path: config/namespace-install
  repoUrl: https://github.com/numaproj/numaflow.git
  targetRevision: main
  kustomize:
    ...
  directory:
    ...
  helm:
    valueFiles:
      - values-1.yaml
      - values-2.yaml
    parameters:
      - name: "service.type"
         value: LoadBalancer
...

```
